apiVersion: skaffold/v4beta7
kind: Config
build:
  local:
    push: false
  platforms: ['linux/amd64', 'linux/arm64']
  artifacts:
    - image: boxyhq/jackson-local
      context: ./
      docker:
        dockerfile: ./Dockerfile
manifests:
  kustomize:
    paths:
      - ./kustomize/overlays/dynamodb
