apiVersion: v1
kind: Service
metadata:
  name: jackson-internal
  namespace: '{{repl ConfigOption "namespace"}}'
  labels:
    app: jackson-internal
    tier: jackson-internal
spec:
  ports:
    - name: original
      port: 5225
      targetPort: 5225
  selector:
    app: jackson
    tier: jackson
