apiVersion: v1
kind: Service
metadata:
  name: jackson-mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jackson-mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: jackson-mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.31
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mysql
            - name: MYSQL_DATABASE
              value: mysql
          ports:
            - name: mysql
              containerPort: 3306
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -u
                - root
                - --password=mysql
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -u
                - root
                - --password=mysql
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
          volumeMounts:
            - name: jackson-mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: jackson-mysql-data
          persistentVolumeClaim:
            claimName: jackson-mysql-data
  volumeClaimTemplates:
    - metadata:
        name: jackson-mysql-data
      spec:
        accessModes:
          - 'ReadWriteOnce'
        resources:
          requests:
            storage: 1Gi
